# Header
nav:
  Home: /
  home:
    path: ./
    icon: mingcute:home-2-fill
    text: Home
  posts:
    path: ./archives
    icon: mingcute:inbox-fill
    text: Posts
  # publications:
  #   path: ./publications
  #   icon: mingcute:science-fill
  #   text: Publications
  # Projects: /projects
  categories:
    path: ./category
    icon: mingcute:classify-2-fill
    text: Categories
  tags:
    path: ./tag
    icon: mingcute:tag-fill
    text: Tags
  about:
    path: ./about
    icon: mingcute:user-info-fill
    text: About

  # To add a new page, use hexo new page, then add another entry below.
  # Each entry MUST have a path. In addition, it will render icon and/or text
  # if they are provided. It will be an empty button if none of these are 
  # provided.

email: amir.m.babaei.academic@gmail.com
my_location: Tehran, Iran
cv_path: /pdf/AmirMohammadBabaei_Academic_CV.pdf
show_featured_posts: true

# News Section Settings
show_news_section: true
news:
  - date: "Sep 27, 2025"
    content: "Weâ€™re delighted to announce that our survey, <a href='https://openreview.net/forum?id=3cbJzdR78B' target='_blank'><i>A Comprehensive Survey on Knowledge Distillation</i></a>, has been accepted and published in <i>Transactions on Machine Learning Research (TMLR)</i>; the preprint is available on <a href='https://arxiv.org/abs/2503.12067' target='_blank'>arXiv</a>."
  - date: "Mar 15, 2025"
    content: "We are pleased to announce the publication of the preprint of our survey, <a href='https://arxiv.org/abs/2503.12067' target='_blank'><i>A Comprehensive Survey on Knowledge Distillation</i></a>, on ArXiv."
  - date: "Jan 19, 2025"
    content: "Our Paper <a href='https://www.sciencedirect.com/science/article/pii/S0262885624004694' target='_blank'><i>CLBSR: A deep curriculum learning-based blind image super resolution network using geometrical prior</i></a> has been accepted at <strong>Image and Vision Computing</strong>."

# favicon
favicon: /images/profile.jpg

# logo
portrait: /images/profile.jpg  # Your profile image here
show_profile_image: true

# links
links:
  Email:
    link: mailto:amir.m.babaei.academic@gmail.com
    icon: mingcute:mail-fill
  Github:
    link: https://github.com/AmirMohamadBabaee
    icon: mingcute:github-fill
  # ZhiHu:
  #   link: https://www.zhihu.com/people/chen-ying-fa-34
  #   icon: ri:zhihu-line
  Twitter:
    link: https://twitter.com/amir_under_dev
    icon: mingcute:social-x-fill
  # You can add more links below using the format above.
  LinkedIn:
    link: https://www.linkedin.com/in/amirmohammad-babaei/
    icon: mingcute:linkedin-fill
  StackOverFlow:
    link: https://stackoverflow.com/users/19718207/amirmohammad-babaei
    icon: mingcute:code-line
  GoogleScholar:
    link: https://scholar.google.com/citations?user=8I5IRE0AAAAJ&hl=en
    icon: mingcute:mortarboard-fill

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: AmirMohamadBabaee/AmirMohamadBabaee.github.io
  repo_id: R_kgDOMG70rQ
  category: Blog Post Comments
  category_id: DIC_kwDOMG70rc4CgHiU
  mapping: pathname
